global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loadgen'
    metrics_path: /metrics
    static_configs:
      - targets: ['loadgen_app_1:8080']
